### ISSUE TITLE
small data entry error

### ISSUE THREAD

**Issue by Victor-GY-Yu** [flother/rio2016#1]
Kevin Cordes' height is listed as 2.21m when he's 6'5/196cm ([on team USA swimming](https://www.teamusa.org/usa-swimming/athletes/Kevin-Cordes)). I don't think it was swapped with another athlete's height as I did a quick Google search for "Olympics kevin cordes 2.21m" and a Yahoo page also had him mistakenly listed at that height.

And thanks for sharing the dataset! Was looking for something like this.

**Comment by flother** [comment]
Thanks Victor. You can see the original error on the [official Rio 2016 page for Cordes](http://web.archive.org/web/20160826104734/https://www.rio2016.com/en/athlete/kevin-cordes). While generally I want the data in this repo to match the original source, it seems obvious that in this case it's wrong. Fixed.
