### ISSUE TITLE
Aslan Kakhidze

### ISSUE THREAD

**Issue by robhop** [flother/rio2016#2]
I have doubts that Aslan Kakhidze were 39 kilos, as he competes in the men's freestyle 86 kg
https://en.wikipedia.org/wiki/Aslan_Kakhidze
His real weight I do not know. 
The parsing seems to be correct, but the source seems wrong 
https://web.archive.org/web/20160922190704/https://www.rio2016.com/en/athlete/aslan-kakhidze

**Comment by flother** [comment]
Well spotted!

I think I can see the problem here: [86 lbs is 39 kg](https://duckduckgo.com/?q=86lbs+in+kg). I would guess that someone entered his weight as "86" but used the wrong unit of measurement. I think we can confidently correct his weight in this repo.
