### ISSUE TITLE
How to scrap data from the Olympics site ?

### ISSUE THREAD

**Issue by bhamadicharef** [flother/rio2016#3]
Hi 

Based on your RIO2016 dataset I would like to ask how did you scrap data from the olympics site ?

For some study I would like to collect SURNAME firstname gender from
https://olympics.com/tokyo-2020/olympic-games/en/results/all-sports/athletes.htm 
they are Athletes, Coaches, Technical Officials, etc.

Any pointers ?

Thank 

Brahim HAMADI CHAREF
Singapore

**Comment by flother** [comment]
Hi Brahim,

To collect all the results I used [Scrapy](https://scrapy.org/), a web-scraping library written in Python. It's exceptionally good at this sort of thing. For other (less ambitious) projects I've also used [Rvest](https://rvest.tidyverse.org/), an R package similar to Scrapy.

As a starting point for your data scraping, you should take a look at the JSON data that's used to make the [athletes page](https://olympics.com/tokyo-2020/olympic-games/en/results/all-sports/athletes.htm) you mention:

<https://olympics.com/tokyo-2020/olympic-games/en/results/all-sports/zzje001a.json>

That contains the unique id, name, nationality, and discipline for each athlete, and a link to a page with further details. For example:

```json
{
    "img": "../../../resOG2020-/img/bios/photos/thumb/1284763.jpg",
    "noc": "IRI",
    "code": "1284763",
    "name": "ABBASALI Hamideh",
    "lnk": "../../../en/results/karate/athlete-profile-n1284763-abbasali-hamideh.htm",
    "orgNOrder": "OC",
    "shortName": "ABBASALI H",
    "dis": "KTE",
    "discNOrder": "null"
}
```

For `lnk`, you can replace `../../..` with `https://olympics.com/tokyo-2020/olympic-games` to get the absolute URL. In the example above it would become <https://olympics.com/tokyo-2020/olympic-games/en/results/karate/athlete-profile-n1284763-abbasali-hamideh.htm>.

I hope that helps you in your data quest. Good luck!

**Comment by bhamadicharef** [comment]
Thank you very much ! Indeed I can see how to scrap the info I need now :-)

**Comment by bhamadicharef** [comment]
Oups I forgot to put some random delay here and there ! Access Denied 
You don't have permission to access "http://olympics.com/tokyo-2020/en/" on this server.
Reference #18.64eb1cb8.1628933327.24fa4eef
